version: '3.7'
services:
  mongo:
    build: ../Produtos
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data/mongo:/data/db
    networks:
      desafio:

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      desafio:

  productapp:
    container_name: dev.products.app
    build: ../
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./data/app:/data/db
    networks:
      desafio:

networks:
  desafio: